# Copyright 2018 The OpenPitrix Authors. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.

language: go

go:
- '1.13'

env:
  global:
    - GO111MODULE=on

go_import_path: openpitrix.io/libconfd

script:
- go test openpitrix.io/libconfd/...
- go vet openpitrix.io/libconfd/...
