# Copyright 2018 The OpenPitrix Authors. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.

TARG:=libconfd-simple-app

.PHONY: help
help:
	@echo "Please use \`make <target>\` where <target> is one of"
	@echo "  check    to check app config"
	@echo "  start    to start app server in docker"
	@echo "  restart  to restart app server in docker"
	@echo "  stop     to stop app server in docker"
	@echo "  clean    to clean the temp files for developement"
	@echo "  help     to show this help informatrion"

.PHONY: check
check:
	@echo "check todo"

.PHONY: restart
restart:
	@echo "restart todo"

.PHONY: start
start:
	@echo "start todo"

.PHONY: stop
stop:
	@echo "todo"


.PHONY: clean
clean:
	@echo "todo"
